### ISSUE TITLE
small issue with ports

### ISSUE THREAD

**Issue by Austpool** [ProjectArepa/ArepaCoin#2]
Hello.
just to remind you the default ports in the coin build are 15715 and 15714, but you web site says 8586/8585. small change for next build to tidy up. cheers.

**Comment by SamaelDNM** [comment]
Hi  @Austpool  because it says it is a mistake, if they are the ports that are mentioned on the web please check here. 

https://github.com/ProjectArepa/ArepaCoin/blob/5fc0e3909861c729aea69c9063afbf33b9ac9067/src/chainparams.cpp#L56

**Comment by SamaelDNM** [comment]
There are no more answers, the issue close
